### PR TITLE
Update 2016-02-16-basics-declarations.md

### PR DESCRIPTION
**Pull request by bsitruk**

### CODE REVIEW

**Comment by loverajoel** [comment]
@adaniloff ping

**Comment by adaniloff** [comment]
Thanks  @bsitruk ! Can i accept the PR from Github UI or should I do it in CLI ?
EDIT : I'm quite new here :)

**Comment by loverajoel** [comment]
@ahmedelgabri merged

**Comment by ahmedelgabri** [comment]
@loverajoel I think you meant @adaniloff :)

**Comment by adaniloff** [comment]
I think too :P @loverajoel , so you are the one that validate PR and just wait for the author to confirm it, right :)? 

Just wanna be sure about the process here.

**Pull request merged**
