### PR TITLE
How to check numbers (include zero) [tip]

### PR DESCRIPTION
**Pull request by DanilaEgorenko**
## Username
https://t.me/danilaEgorenko

### CODE REVIEW

**Comment by tracker1** [comment]
And if your starting value is `-1`?

```
const isNumber = (num) => typeof num === "number" && !Number.isNaN(num);
```

The above function will test that the value is a number, and is not NaN.

**Comment by DanilaEgorenko** [comment]
Usually -1 is a false value (e.g. when iterating over an array)
The construction presented by you is rather cumbersome, my counterpart is rather 'light'.
If -1 is a valid value in your program, just add
```
if (num + 1 || num === -1) {...}
```

**Comment by tracker1** [comment]
`num + 1` will be truthy for literally any value... `(false +1 === 1)`  `(null + 1 === 1) ` etc.

**Comment by gromgit** [comment]
> `num + 1` will be truthy for literally any value... `(false +1 === 1)` `(null + 1 === 1) ` etc.

_Almost_ any value. The following are all falsy:
```
-1 + 1 === 0
NaN + 1 === NaN
undefined + 1 === NaN   // undefined === NaN in a number context
```

**Comment by DanilaEgorenko** [comment]
Ok guys. What about the frequent case of converting an array to a map? It's incredibly convenient

**Comment by tracker1** [comment]
@DanilaEgorenko you're actually running `console.log` for the undefined value, it just isn't printing anything...

**Comment by DanilaEgorenko** [comment]
but I dont use console :/

**Comment by tracker1** [comment]
@DanilaEgorenko Your code/example is... the point is, the example provided isn't really fit for the purpose.

**Pull request closed without merging**
