### PR TITLE
Hotfix/tip 2 math round fix

### PR DESCRIPTION
**Pull request by crecotun**
Fixed annoying Liquid warning in all translates:
Liquid Warning: Liquid syntax error (line 25): Expected end_of_string but found open_round in "{{Math.random()}}"

### CODE REVIEW

**Comment by crecotun** [comment]
Ups, It added my translates too =/

**Comment by crecotun** [comment]
Ok, it'll be fixed with release of russian translation
Or you can fix it by yourself

**Comment by crecotun** [comment]
The poins is to wrap code in `{% raw %} {% endraw %}`

`<div key={% raw %}{{item.key}}{% endraw %}>{% raw %}{{item.name}}{% endraw %}</div>`

`<MyComponent key={% raw %}{{item.key}}{% endraw %}/>`

`<MyComponent key={% raw %}{{Math.random()}}{% endraw %}/>`

**Comment by loverajoel** [comment]
@Krekotun ok, good catch, I will take a look! thanks

**Pull request closed without merging**
