### PR TITLE
Add JSPerf to Tip #18

### PR DESCRIPTION
**Pull request by timjrobinson**
If a tip is about performance it should really have numbers to back up its claim.

### CODE REVIEW

**Comment by loverajoel** [comment]
@pklinger ping!

**Comment by pklinger** [comment]
Hi, we've come across this previously @timjrobinson. Have a look at [this](http://rocha.la/JavaScript-bitwise-operators-in-practice) and  #85 . But I appreciate your PR for improvements.

**Comment by timjrobinson** [comment]
Sure any link is fine, just needs some benchmarks.

**Comment by pklinger** [comment]
@timjrobinson also be aware of #104 latest results seem to differ from past tests

**Comment by homer0** [comment]
I like this, even if you think you should always use `Math.floor` for better readability it's always nice to see the numbers: http://jmp.sh/4aUhv8H (Chrome, Firefox, Opera, Safari and iOS).

Also, the post on [rocha.la](http://rocha.la/JavaScript-bitwise-operators-in-practice) it's 4 years old, and being the discussion about performance, I don't think it's relevant.

**Comment by zenopopovici** [comment]
@timjrobinson Can you please rebase your work? We can review and merge it then.

**Pull request closed without merging**
