### PR TITLE
update pr#135 Speed up recursive functions with memoization

### PR DESCRIPTION
**Pull request by hingsir**
## TL;DR;

Recursive functions are used in many situations e.g. fibonacci, GCD or factorial. If improperly used, they would perform badly. This tip will tell you how to improve the performance.
## Username

[@hingsir](https://github.com/hingsir)

### CODE REVIEW

**Comment by loverajoel** [comment]
@hingsir  hey use the PR template -> https://github.com/loverajoel/jstips/blob/gh-pages/GIT_TEMPLATE.md

**Comment by hingsir** [comment]
@loverajoel Is that ok?

**Comment by loverajoel** [comment]
@hingsir :+1:

**Comment by loverajoel** [comment]
thanks man!

**Pull request merged**
