### PR TITLE
Revamped Tip 18

### PR DESCRIPTION
**Pull request by gromgit**
## TL;DR;

`~~X == Math.trunc(X)`...in certain cases
## Username

[gromgit](https://github.com/gromgit)
## Extra
- Changed "round" to "trunc" (the former is quite different)
- Restructed the tip into appropriate sections
- Greatly expanded on the pros and cons

NOTE: I've changed the tip name and TL;DR for accuracy, but I did **not** rename the file itself.

### CODE REVIEW

**Comment by kurtextrem** [comment]
​Perfect, :shipit:!​

**Comment by zenopopovici** [comment]
Nice! We'll review it.

**Comment by loverajoel** [comment]
@pklinger ping here!

**Comment by gromgit** [comment]
Thanks for the feedback, @pklinger . I've made further adjustments that hopefully improve the tip.

**Comment by pklinger** [comment]
Thanks, I appreciate your contributions :shipit:

**Comment by loverajoel** [comment]
awesome guys :clap: @pklinger @gromgit

**Pull request merged**
