### PR TITLE
Get the file extension

### PR DESCRIPTION
**Pull request by richzw**
## TL;DR;

Several solutions are posted here to get the more efficient way to get the file extension.
## 

 [@richzw](https://github.com/richzw)

### CODE REVIEW

**Comment by kurtextrem** [comment]
Great tip.

:shipit:

**Comment by loverajoel** [comment]
nice :shipit:

**Comment by sjfkai** [comment]
:shipit:

**Comment by neighborhood999** [comment]
:shipit:

**Comment by zenopopovici** [comment]
:shipit: . Nice work!

**Comment by gromgit** [comment]
A couple of issues:

Your _How does it _work?_ section is a _word-for-word copy_ of the linked StackOverflow answer. You should probably rewrite it in your own words to avoid accusations of plagiarism. (The other reason to do so is that the original explanation actually leaves out a couple of details.)

You should also make a note that `getFileExtension3()` is the only _correct_ implementation of the three. I suggest making a table of the results of all three functions called over all your test strings, so that the differences become obvious.

**Comment by richzw** [comment]
@gromgit, thank you for your comments, I have updated this tip per your suggestion.

**Comment by loverajoel** [comment]
@richzw thanks for your tip! really good tip!

**Pull request merged**
