### PR TITLE
Creating immutable objects

### PR DESCRIPTION
**Pull request by emars**

### CODE REVIEW

**Comment by homer0** [comment]
This is another case of quoting the docs, but the **Unapply attacks** part was pretty interesting; I think you should make your tip about it, instead of `Creating immutable objects`, `How to prevent unapply attacks` :).

@loverajoel

**Comment by mallowigi** [comment]
You should mention that freeze is not recursive, e.g. if my object have nested objects in it, these are not frozen.

**Comment by loverajoel** [comment]
Hi, how you can see the jstips repository changed his format and the `master` branch now is `gh-pages`, now are based in _jekyll blog format_. You can see live here => [jstips.com](http://www.jstips.co/)
For that reason you should update your tip with this [instructions](https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING.md).

Let me know if you need some help or have suggestion. All are welcome!

Thanks

**Comment by loverajoel** [comment]
Hey @emars I like this tip but yes i'm agree with @homer0 if you can change the focus of the tip to _unapply attacks_ will be useful.

**Comment by loverajoel** [comment]
@emars ping!

**Comment by emars** [comment]
Sounds good! I'll update it today.

**Comment by loverajoel** [comment]
@emars ping!

**Comment by emars** [comment]
hey my bad, I set aside some time to update it tomorrow morning. for real this time.

**Comment by emars** [comment]
Since it's now being applied to the `gh-pages` , would I need to create a new PR for the updated tip?

**Comment by loverajoel** [comment]
@emars yes, you have to create a new pr, sorry

**Comment by emars** [comment]
sure no worries.

**Pull request closed without merging**
