### PR TITLE
3 Array Hacks

### PR DESCRIPTION
**Pull request by helfi92**
## TL;DR;
Arrays are everywhere in JavaScript and with the new [spread operators](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator) introduced in ECMAScript 6, you can do awesome things with them. In this post I will show you 3 useful tricks you can use when programming.
## Username
[@hassanhelfi](https://twitter.com/hassanhelfi)

### CODE REVIEW

**Comment by kurtextrem** [comment]
Cool! :shipit:

**Comment by neighborhood999** [comment]
@helfi92 I recommend to use `const` or `let` instead of `var`. 😄

**Comment by zenopopovici** [comment]
Nice :shipit:, but yea, use `const` or `let`

**Comment by helfi92** [comment]
@zenopopovici @neighborhood999 Good catch. Pushed my changes.

**Comment by loverajoel** [comment]
@helfi92 wonderful tip! Thanks! 🙌

**Pull request merged**
