### PR TITLE
Revamped Tip 33

### PR DESCRIPTION
**Pull request by gromgit**
## TL;DR;

Compact one-liners that generate ordinal sequence arrays
## Username

[gromgit](https://github.com/gromgit)
## Extra
- Substituted a proper (though long) explanation

### CODE REVIEW

**Comment by loverajoel** [comment]
@SarjuHansaliya please take a look here!

**Comment by adaniloff** [comment]
I find this interesting, but isn't jstips about short explanation ? 

```
With less than 2 minutes, you will be able to read about performance, conventions, hacks, interview questions and all the items that the future of this awesome language holds for us.
```

Could it be added with a link that explain all that, and keep here necessary stuff only?

**Comment by gromgit** [comment]
@adaniloff Fair enough. I've created #313 to address this, though I won't close this just yet.

**Comment by SarjuHansaliya** [comment]
@gromgit  Thanks for nice write up.

**Comment by zenopopovici** [comment]
@SarjuHansaliya Can we agree to merge #313 or #307? (It's really your decision).

**Comment by SarjuHansaliya** [comment]
@zenopopovici I think it would be better if we merge #313.

**Comment by loverajoel** [comment]
closed, we merge https://github.com/loverajoel/jstips/pull/313

Thanks

**Pull request closed without merging**
