### PR TITLE
Fix - shuffledArray var declr

### PR DESCRIPTION
**Pull request by 0xmtn**

### CODE REVIEW

**Comment by loverajoel** [comment]
mergeback

**Comment by 0xmtn** [comment]
Mergeback where? Sorry, couldn't understand.

**Comment by loverajoel** [comment]
I can merge this fix, you should make a mergeback or rebaase

**Comment by 0xmtn** [comment]
Sorry for misunderstanding @loverajoel, long days, no sleep, forgot that you already published two more tips.

**Comment by zenopopovici** [comment]
@0xmtn Your merge is not OK, you have still GIT merge markers in place.

E.g.:
`<<<<<<< d5840b8e0bbd664aa60726ae506cd0f2d26bf9e1`

Please fix so we can merge.

**Pull request closed without merging**
