### PR TITLE
Update 2016-01-26-filtering-and-sorting-a-list-of-strings.md

### PR DESCRIPTION
**Pull request by m-shulipa**
- Use lastIndexOf instead of IndexOf
- use third parameter in .filter function. It will avoid search in closure and make this function more independent
- optimize sort function: use ternary operator instead of if-s. In any case, 'esle' statement is redundant there.

### CODE REVIEW

**Comment by loverajoel** [comment]
@davegomez ping!

**Comment by davegomez** [comment]
I'll change it this Saturday, I'm kind of busy right now.

And thanks for the suggestions, they are great.

**Comment by loverajoel** [comment]
@davegomez  I can merge this if you give me the 'ok'

**Comment by davegomez** [comment]
Of course @loverajoel, no problem at all

**Comment by davegomez** [comment]
Well, I just checked the suggested changes and I have some objections.
1. There's no clear gain in using `lastIndexOf()` instead of `indexOf()` but maybe a 3% performance improvement. I can't see any problem on using it either.
2. I can't see the point of the third param suggestion, maybe I didn't understand what you are trying to suggest about the closures and the use of the self keyword is misleading and confusing.
3. Adding a nested ternary operator won't make the function more optimal but confusing and nested ternaries are considered bad style. On the other matter, if I remove the `else` statement the resulted "sorted" array will be something like this:

```
["continue", "abstract", "break", "catch", "class", "const", "delete", "case", "debugger", "byte", "char", "boolean", "arguments", "default", "with", "in", "for", "new", "try", "false", "super", "throw", "while", "var", "export", "import", "return", "switch", "typeof", "do", "extends", "finally", "if", "else", "function", "int", "enum", "null", "goto", "long", "final", "float", "short", "double", "native", "public", "static", "throws", "this", "package", "private", "true", "volatile", "interface", "protected", "transient", "implements", "instanceof", "synchronized", "let", "eval", "yield", "void", "await"]
```

I prefer to not merge these suggestions @loverajoel

**Comment by zenopopovici** [comment]
This has been merged.

**Pull request closed without merging**
