### PR TITLE
Hash maps with no side effects

### PR DESCRIPTION
**Pull request by bhaskarmelkani**
## TL;DR;
Create hash maps(without side effects) using `Object.create(null)`
## Username
[@bhaskarmelkani](https://www.twitter.com/bhaskarmelkani)

### CODE REVIEW

**Comment by kurtextrem** [comment]
However, watch the performance: https://jsperf.com/object-create-null-vs-literal/27
Using ES6's `Map` might be even more performant.

**Comment by zenopopovici** [comment]
This should be merged. It's a good tip. :shipit:

**Comment by bhaskarmelkani** [comment]
Any update on this ?

**Comment by zenopopovici** [comment]
@loverajoel ?

**Review by zenopopovici — APPROVED** [review]
Looks Ok to me.

**Comment by bhaskarmelkani** [comment]
Snooze :)

**Comment by 1robertrb** [comment]
why does the example use `let` ? there's no reassignment, `const` feels more appropriate. 
<del>a shout out to `Map` seems relevant here too. </del> there's a shout at the very end, to Map and friends.

**Comment by zenopopovici** [comment]
Guys can we merge this? @loverajoel, @sjfkai, @neighborhood999, @aschelstraete

**Comment by sjfkai** [comment]
Looks good to me 👍

**Comment by neighborhood999** [comment]
As @r-obert say it, I think use `let` instead of `const` to avoid confusing.

**Review by neighborhood999 — COMMENTED** [review]
As @r-obert say it, I thinking use `let` instead of `const` to avoid confusing.

**Comment by 1robertrb** [comment]
`let` isn't used anymore :+1:

**Comment by 1robertrb** [comment]
oh, maybe you meant `let` is less confusing? could be, not sure. probably doesn't matter much.
i think eventually, as browsers support 'const' and 'let' natively, optimisations might be applied if it is known a "variable" cannot be reassigned. so probably a good practice to not ask for reassignment if it is not needed.

**Comment by neighborhood999** [comment]
@r-obert Thanks for your explaining!

**Comment by zenopopovici** [comment]
Guys: I don't know exactly how the merge must be done, we should move ahead without Joel if he's not available.

**Comment by bhaskarmelkani** [comment]
I guess its not a big topic to discuss, so we should close(merge/not merge) and move forward. :)

**Comment by 1robertrb** [comment]
:shipit: ⏲

**Comment by zenopopovici** [comment]
First time I merge a tip. Hopefully all goes well :)

**Comment by zenopopovici** [comment]
Some issues. Correcting them now.

**Comment by zenopopovici** [comment]
Success.

**Comment by bhaskarmelkani** [comment]
👍

**Pull request merged**
