### PR TITLE
Tip proposal: remove dupl. prim. values from Array

### PR DESCRIPTION
**Pull request by danillouz**
## TL;DR;

Tip illustrates how to remove duplicate primitive values from an Array.
## Username

[@danillouz](https://twitter.com/danillouz)

### CODE REVIEW

**Comment by loverajoel** [comment]
@danillouz hey take a look [here](http://stackoverflow.com/a/9229821/2313726)

Can you add some of this? I like this tip

**Comment by danillouz** [comment]
@loverajoel good stuff! learned some new things myself :) How about I expand the tip to also include deduplicating primitives and link to the SO answer as a reference. Maybe you can review it when you have the time and we can iterate on it if necessary. What do you think?

**Comment by loverajoel** [comment]
@danillouz yes sure!

**Comment by loverajoel** [comment]
@danillouz  ping!

**Comment by danillouz** [comment]
@loverajoel sorry, am swamped with work! I'll do my best to send a pull request tomorrow!

**Comment by danillouz** [comment]
@loverajoel hi, I updated the tip and included a way to deduplicate Objects. Added some references, among of them, the SO answer you provided. I also added the way to dedup using a `Set` which is really cool I think!

I did leave out anything about performance though.  First of all I couldn't reproduce the statements made about performance in the SO answer. Even though it's true that in theory a sequential search (using `filter` with `indexOf`) is less performant that doing a direct lookup (hash table), I believe the engine is heavily optimizing methods like `filter` and `indexOf`. In my test cases the implementations where a hash table was used, were actually the slowest.
Second, IMO it's a bit out of scope. I mean, it's all about tips and I think when we start to talk about performance we start to complicate things because we also need to include info about how we tested stuff and show specific results to prove this. I think this could be a post by itself.
But if you think this would be important to add, maybe you can advise me how to approach this to keep it simple.

Please review my changes when you have the time and let me know what you think.

**Comment by loverajoel** [comment]
So beautiful tip! clear and useful!
I agree with you about performance hover this tip, don't worry!
Thanks @danillouz !

**Comment by danillouz** [comment]
@loverajoel Thanks! Glad you like it! Was really cool to contribute to your awesome project!

**Pull request merged**
