### PR TITLE
patch: Converting miliseconds to Second as Unix timestamp is calculat…

### PR DESCRIPTION
**Pull request by nurrony**
## TL;DR;

In Javascript you can easily get the unix timestamp
## Username

@nmrony
## Extra

Converting miliseconds to seconds as Unix timestamp is calculaed in seconds

### CODE REVIEW

**Comment by kurtextrem** [comment]
It's probably worth adding https://github.com/loverajoel/jstips/issues/293#issuecomment-189654261

**Comment by nurrony** [comment]
@kurtextrem Hmm, Will add a paragraph on it after confirmation of next comment

**Comment by loverajoel** [comment]
:shipit:

**Comment by zenopopovici** [comment]
:shipit:

**Comment by sjfkai** [comment]
For the sake of readability, is `Math.floor()` better than `~~` ?

**Comment by gromgit** [comment]
@sjfkai @nmrony For the sake of **accuracy**, `Math.floor()` should **always** be used over `~~`. Since `~` is defined to work over 32 bits, `~~` actually causes a Y2038 issue:

``` js
    a= +new Date('2040-01-01') / 1000 + 0.123
==> 2208988800.123
    ~~a
==> -2085978496  // Oops
    Math.floor(a)
==> 2208988800
```

**Comment by sjfkai** [comment]
@gromgit :+1:

**Comment by zenopopovici** [comment]
@nmrony, @gromgit has a point. I would also go for `Math.floor`. What do you think?

**Comment by nurrony** [comment]
@zenopopovici @gromgit Sure!! I will give this patch a final touch when I return home .

**Comment by nurrony** [comment]
@zenopopovici Updated `PR` with `Math.floor` and working date string format to grab timestamp of specific date for iOS devices

**Comment by gromgit** [comment]
@nmrony I think there's some confusion regarding the recent discussions in #293 .

It's not that Safari on iOS devices has a brain-damaged `Date()` that requires full ISO 8601 timestamp strings; it's that **single-digit days and months** aren't reliably parsed across platforms. For instance, the venerable Firefox on _all desktop and mobile platforms_ fails to parse `2016-2-28`, but no JS implementation of `Date()` in recorded history has ever choked on `2016-02-28`.

The key statement should probably read as follows:

To get the Unix epoch value (seconds since midnight 1 Jan 1970 UTC) of a specific date, pass `YYYY-MM-DD` (4-digit year, 2-digit month and day) as a parameter to the `Date` constructor.

**Comment by nurrony** [comment]
@gromgit  I have already mentioned it in updated PR

**Comment by gromgit** [comment]
@nmrony Sorry, I wasn't clear. What I mean to say is that `YYYY-MM-DD` and `YYYY-MM-DDT00:00:00Z` are _universally understood_ `Date()` input formats. The phrase "for iOS devices" is completely unnecessary, and may in fact confuse readers into believing that some other format is required for JS on Android or other platforms.

**Comment by nurrony** [comment]
@gromgit Okay. Let me update the PR right away. Hopefully we can ship it after this update :smiley:

**Comment by nurrony** [comment]
@gromgit @kurtextrem @sjfkai @zenopopovici Please can you review? Hopefully it is okay now. If it is please add :shipit: :wink:

**Comment by gromgit** [comment]
:shipit:

**Comment by loverajoel** [comment]
:clap: :clap: :clap:

**Comment by kurtextrem** [comment]
:shipit:

**Comment by loverajoel** [comment]
merged, thanks guys!

**Pull request merged**
