### PR TITLE
Use optional arguments in functions

### PR DESCRIPTION
**Pull request by alphashuro**
## TL;DR;

You can make function arguments and callback optional
## alphashuro

[@alphashuro](https://twitter.com/alphashuro)
[alphashuro](https://github.com/alphashuro)

### CODE REVIEW

**Comment by loverajoel** [comment]
ok, I like this :shipit:

**Comment by zenopopovici** [comment]
Nais :shipit:

**Comment by kurtextrem** [comment]
Please don't leak arguments: https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

**Comment by alphashuro** [comment]
Thank you @kurtextrem , good catch, I did not know there were rules about leaking arguments. I will fix that tonight and update the PR

**Comment by alphashuro** [comment]
I've updated the code, any thoughts?

**Comment by kurtextrem** [comment]
:shipit: :+1:

**Comment by sjfkai** [comment]
:shipit:  👍

**Comment by zenopopovici** [comment]
:shipit:

**Pull request merged**
