### PR TITLE
Update 2017-03-29-recursion-iteration-and-tail-calls-in-js.md

### PR DESCRIPTION
**Pull request by 4xiom5**
## TL;DR;
```js
function factorial(n) {
    function inner_factorial(n, res) {
        if (n === 0) {
            return res;
        }
        return inner_factorial(n - 1, res * n);
    }
    return inner_factorial(n, 1);
}
```
to
```js
function factorial(n) {
    return (function inner_factorial(n, res) {
        if (n === 0) {
            return res;
        }
        return inner_factorial(n - 1, res * n);
    })(n,1);
}
```
## Username
Github : [BNedry](https://github.com/BNedry)

### CODE REVIEW

**Comment by kurtextrem** [comment]
Explaining the benefit is a part of a tip, please add that :)

**Comment by 1robertrb** [comment]
what's the reason to change? first version is easier to understand.

**Comment by BNedry** [comment]
Using functionalities of javascript which seems to be the purpose of this repository

**Comment by 4xiom5** [comment]
Well, the second one is not that hard to understand and follow a bit more the DRY rule

**Comment by zenopopovici** [comment]
Th think the first one is easier to understand. Let's keep it that way.

**Pull request closed without merging**
