### PR TITLE
Currying vs partial application

### PR DESCRIPTION
**Pull request by bhaskarmelkani**

### CODE REVIEW

**Comment by kurtextrem** [comment]
I'm not sure if this is a "tip". It doesn't give any concrete example how this improves your code. If you find some fancy function where jQuery applies that (or some other framework) and add that to your tip it would be more helpful.

My comment is not meant to offend.

**Comment by bhaskarmelkani** [comment]
Great, will check if I can make it helpful in some way. Also, will take care of this for my next contributions.

Thanks a lot for a prompt response :).

**Comment by FagnerMartinsBrack** [comment]
Just out of curiosity. Recently I was developing an object oriented response for a unit-test module where I ended up using currying as a setter for changing a specific object property. I had this response that were used in several parts of my test and I wanted to keep it DRY due to the huge ammount of repetitive calls:

``` javascript
var response = function() {
  return responseBehaviorToBeTested({
    id: response._id || /* default */ 123
  });
};
response.id = function( id ) {
  this._id = id;
  return this;
};
```

Detailed fiddle: https://jsfiddle.net/bheqfbhf/2/

Just ignore the obvious flaws, like of assigning a cross-instance property to the function reference or depending upon the variable name that is declared. It is at least an interesting use case to be explored because it allows customizing other inputs later without changing any code.

**Comment by loverajoel** [comment]
Hi, how you can see the jstips repository changed his format and the `master` branch now is `gh-pages`, now are based in _jekyll blog format_. You can see live here => [jstips.com](http://www.jstips.co/)
For that reason you should update your tip with this [instructions](https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING.md).

Let me know if you need some help or have suggestion. All are welcome!

Thanks

**Comment by bhaskarmelkani** [comment]
Closing this in favor #167

**Pull request closed without merging**
