### PR TITLE
Fix Tip #35 Chinese version

### PR DESCRIPTION
**Pull request by zhangpenglin**
> P.S.: If variable1 is a number, then first check if it is 0.

`number` should translate to `数字`

### CODE REVIEW

**Comment by loverajoel** [comment]
@neighborhood999 ping

**Comment by neighborhood999** [comment]
I think this PR need @sjfkai review beacause this version is **zh_CN**
what do you think @loverajoel ?

**Comment by loverajoel** [comment]
@neighborhood999 sorry, my bad

**Comment by sjfkai** [comment]
@zhangpenglin Thank you.  Except more PR to help me improve  the zh_CN version.

**Pull request merged**
