### PR TITLE
tip: even simpler way of use indexOf as a contains clause

### PR DESCRIPTION
**Pull request by jhogoforbroke**

### CODE REVIEW

**Comment by jhogoforbroke** [comment]
Ow sorry, too late. I think that would be 8 now

**Comment by hingsir** [comment]
awesome,  but dot not think it's better readable for beginners.

**Comment by jhogoforbroke** [comment]
hi @hingsir! but it's so simple to understand and use. can you suggest me another title maybe?

**Comment by loverajoel** [comment]
I like this one, maybe you can update the title and we can merge this

**Comment by jhogoforbroke** [comment]
@loverajoel update title for even simpler way of use indexOf as a contains clause

**Comment by indianakernick** [comment]
Why would you use indexOf when you can use includes. It's as readable as you can get

**Comment by jhogoforbroke** [comment]
includes are amazing, but for arrays is part of the ECMAScript 2016 (ES7) proposal, syntax and behavior is subject to change. Even in string is not fully supported in browser compatibility, the recomended [Polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) uses indexOf behind:

``` javascript
if (!String.prototype.includes) {
  String.prototype.includes = function() {'use strict';
    return String.prototype.indexOf.apply(this, arguments) !== -1;
  };
}
```

It is very useful know indexOf

**Comment by loverajoel** [comment]
@jhogoforbroke can you make a rebase or mergeback?

**Comment by jhogoforbroke** [comment]
@loverajoel done!

**Comment by loverajoel** [comment]
@jhogoforbroke thanks men!

**Pull request merged**
