### PR TITLE
Create Why you should use Object.is() in Equality Comparison in JavaScript

### PR DESCRIPTION
**Pull request by TarekAlQaddy**
## TL;DR;
a good solution for the looseness of equality comparisons in javascript
## TarekAlQaddy
[@TarekAlQaddy](https://github.com/TarekAlQaddy)

### CODE REVIEW

**Comment by loverajoel** [comment]
Nice tips! Thanks @TarekAlQaddy 👍

**Comment by TarekAlQaddy** [comment]
Thanks @loverajoel

**Comment by kurtextrem** [comment]
Thank you for the contribution, however, is this a tip? For me it seems like this is more useful for edge cases.
In addition, this might have lower perf as it is a function call vs. native syntax. For newbies that are subscribed to jstips this might look like "always use `Object.is` instead of `===`".

**Comment by TarekAlQaddy** [comment]
@kurtextrem 
Thanks for your interest,
When the native syntax lacks that kind of strictness, The function call would be a good replacement and I think that's why they made Object.is in ES6.
for newbies what I meant that if they only want a strict version of comparisons they should go with it yes.
in java for example we sometimes use Object.equals in comparisons.

**Comment by 1robertrb** [comment]
besides NaN, are there other cases `Object.is` handles that `===` does not?

**Comment by TarekAlQaddy** [comment]
@r-obert as I mentioned there is also -0 === +0 which gives true but by Object.is it's false

You can check Mozilla reference 
http://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness

**Comment by 1robertrb** [comment]
thanks @TarekAlQaddy

**Pull request merged**
