### PR TITLE
Fix shuffle usage error

### PR DESCRIPTION
**Pull request by mvedie**
Fix error when peopole make a bad copy / paste .

Slice make a clone of the array, so shuffled returned array must be pushed in a var.

### CODE REVIEW

**Comment by loverajoel** [comment]
@0xmtn ping!

**Comment by 0xmtn** [comment]
https://github.com/loverajoel/jstips/pull/147 - Changed.
It was not actually a bad copy/paste. It was tested, and the output  was from browser inspector. I thought it'd be decision of the user whether to push it to a var or not, when I noticed it ;)

**Comment by mvedie** [comment]
This is not a problem because tips have been removed , but : 

https://jsfiddle.net/8thfq94p/

**Comment by mvedie** [comment]
But if you copy/paste the code directly in chrome console , the standard comportement of the console is to display the returned result of the last call. It's not a good method to test ;)

**Comment by 0xmtn** [comment]
:thumbsup:

**Comment by zenopopovici** [comment]
This is handled in another PR

**Pull request closed without merging**
