### PR TITLE
Using the 'in' operator instead of manually checking the variable and the object

### PR DESCRIPTION
**Pull request by dislick**
I think the `in` operator increases readability.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/in

### CODE REVIEW

**Comment by kurtextrem** [comment]
Personally I'd switch it to `if (colorObj[color])`.

**Comment by loverajoel** [comment]
@AlbertoFuente ping

**Comment by AlbertoFuente** [comment]
@dislick is a good improvement, also the one proposed by @kurtextrem, @loverajoel if you want to add it to the tip for me it's ok, thanks for improvements :+1:

**Comment by loverajoel** [comment]
@dislick @kurtextrem @AlbertoFuente thanks!

**Comment by kurtextrem** [comment]
Relevant jsperf: http://jsperf.com/in-vs-array-syntax1/2

**Pull request merged**
