### PR TITLE
Fix tip 00 with more stats

### PR DESCRIPTION
**Pull request by jeremyfourna**
## Fix tip 00 with more data

Following issue #257 and the comments I made a PR to add more data about the tips.
It's purely about performance on Mobile or desktop.
## dexterneo

[dexterneo](https://github.com/dexterneo)

### CODE REVIEW

**Comment by zenopopovici** [comment]
Nice, real data to compare performance, easy to understand. I've gone trough it and I can't find any issues.
:shipit:

**Comment by loverajoel** [comment]
@dexterneo awesome work, can you add the link to jsperf? (for curious people) or add the browser version, this measures will change in the time

**Comment by jeremyfourna** [comment]
Regarding the stats it's the average of browser by family (Chrome = all versions of Chrome currently on the market, etc...)

The link is already there at the beginning of all the big parts... Do you want to see it for each stats (by browser) ?

I can add the date for each stats, this way when we'll look at it we'll know that is was in february 2016 ?

Tell me what do you prefer ?

**Comment by zenopopovici** [comment]
@dexterneo Just add the browser version for each stats item. (e.g. IE 11, Chrome 44) You can add also the date if you wish.

**Comment by loverajoel** [comment]
+1

**Comment by jeremyfourna** [comment]
OK I'll push another version.

**Comment by jeremyfourna** [comment]
I just commited another version with browser version but I think we have a problem with **jsperf**

On Google Chrome blog, they talk about the next version of Chrome mobile v47 & v48 but on **jsperf** there is only v33 for Chrome mobile, so this page with benchmark with all the browser might be already deprecated lol

I don't know how **jsperf** works to add new browser support etc...

**Comment by zenopopovici** [comment]
I think it's good enough right now.

**Comment by zenopopovici** [comment]
Thanks for your work!

**Comment by jeremyfourna** [comment]
your welcome

**Pull request merged**
