### PR TITLE
Square brackets notation instead of eval

### PR DESCRIPTION
**Pull request by frikinside**
## TL;DR;

Eval is possibly the most misused function in JavaScript, we use it to execute code in a string dynamically but most of the times we just don't need it. Square brackets notation as property accesors could be a proper alternative.
## frikinside

[frikinside](https://github.com/frikinside)
## Extra

I made the branch after start with the translate so don't be afraid about that creations and deletions in commits.
Also, my english is not a professional level so maybe something isn't fully understandable

### CODE REVIEW

**Comment by yuvarajvemula** [comment]
Brackets mean.. What brackets ??

**Comment by frikinside** [comment]
**Square** brackets!
I didn't think it would be necesary to say it explicitly. I can update it with no problems!

**Comment by drakmail** [comment]
Maybe better way is define functions not in global scope, but in isolated scope, like this:

``` javascript
function operationHub(operation){
  var functions = {
    oneOperation: function() { /* some code & logic */ },
    anotherOperation: function() { /* some code & logic */ },
    justAnotherGenericOperation: function() { /* some code & logic */ },
  }
  functions[operation]();
}
```

**Comment by loverajoel** [comment]
+1 to @drakmail

**Comment by zenopopovici** [comment]
@frikinside Ping.

**Comment by zenopopovici** [comment]
Closed due to inactivity.

**Pull request closed without merging**
