### PR TITLE
Update contributing to include details about the title

### PR DESCRIPTION
**Pull request by kurtextrem**
As discussed in #289 I've added details about the titles.

I'm not sure about capitalization. Let's discuss about it :)

Oh and while we're at it: How useful are the dates (e.g. for file names and more)? Isn't simply counting up a better idea (like the main readme does already)?

### CODE REVIEW

**Comment by zenopopovici** [comment]
@kurtextrem Can we gat rid of the `<sup>`? Just use regular () or a comma.

**Comment by zenopopovici** [comment]
I would also add: 

After the tip is reviewed by 5 people and they gave their shippit emote vote (:shipit:), then the tip will be `ready to merge`

**Comment by kurtextrem** [comment]
sure.

**Comment by zenopopovici** [comment]
@kurtextrem Can you please add: Please note that your title cannot start with a backtick character. Then we can merge.

**Comment by gromgit** [comment]
I don't think title-style capitalization should be a formal rule, because I feel the tip names serve as _content summaries_ rather than headlines. Compare, for instance, Tip 20's current:

**Return objects to enable chaining of functions**

vs. the proposed:

**Return Objects to Enable Chaining of Functions**

I personally find the first far more readable than the second.

**Comment by kurtextrem** [comment]
That is a good point, thanks for the feedback.

**Comment by kurtextrem** [comment]
@zenopopovici Added.
Also added how to use ``` blocks correctly for the tips :D

Please also discuss "How useful are the dates (e.g. for file names and more)? Isn't simply counting up a better idea (like the main readme does already)?"

**Comment by loverajoel** [comment]
:shipit: :clap: :clap: :clap:

**Comment by gromgit** [comment]
I think the tip number would be better than a date as the filename prefix, unless your publication backend needs dates in filenames for some reason. This way, the initial filename would be `xx-name-of-your-tip`.

Also, since the Notes section instructs submitters to:

> Leave the date and the tip number with xx.

I would suggest also setting the `tip_number` in `POST_TEMPLATE.md` to `xx`. This should help to avoid confusion.

**Comment by zenopopovici** [comment]
@gromgit Changing the file name now would involve a lot of work across all languages, breaking also Google incoming links. We're sticking to what we have now.

@kurtextrem Please also remove capitalization requirement, @gromgit has a point, besides almost all others are not capitalized. We should stick to non capitalized titles (this should be a requirement).

**Comment by kurtextrem** [comment]
I've in-cooperated the suggested changes now.

**Comment by gromgit** [comment]
Sorry, @zenopopovici , I don't agree with mandating _any_ sort of title casing. This should instead be taken on a case-by-case basis; sometimes all-lower-case reads better, sometimes Headline-Style Casing works, and sometimes a mix is the best option, like the alternate title for my initial PR that conflicted with Tip 18:

### _Double Bitwise NOT_ Considered Harmful: A thorough analysis

**Comment by zenopopovici** [comment]
Thank you @kurtextrem.

**Pull request merged**
