### PR TITLE
Public, private, static, prototype properties in JS

### PR DESCRIPTION
**Pull request by bhaskarmelkani**

### CODE REVIEW

**Comment by indianakernick** [comment]
ES6?

**Comment by bhaskarmelkani** [comment]
No, this is without ES6.

**Comment by yuvarajvemula** [comment]
private???

**Comment by yuvarajvemula** [comment]
Private keyword in JavaScript is just reserved for future use .. Now it doesn't have any use in js ...

**Comment by yuvarajvemula** [comment]
And also I don't sure about other key words mentioned in this topic heading .. Except static  and prototype

**Comment by bhaskarmelkani** [comment]
Check this out :
http://phrogz.net/JS/classes/OOPinJS.html

**Comment by loverajoel** [comment]
Hi, how you can see the jstips repository changed his format and the `master` branch now is `gh-pages`, now are based in _jekyll blog format_. You can see live here => [jstips.com](http://www.jstips.co/)
For that reason you should update your tip with this [instructions](https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING.md).

Let me know if you need some help or have suggestion. All are welcome!

Thanks

**Comment by yuvarajvemula** [comment]
@bhaskarmelkani ,please check out our repositories issues for issue named with best way to write classes in js.   I seen the link you mentioned in your comment.. It's nice but old.. 
Now we have native classes in java script (new in es6) .. Please refer that issue...
And here ,the issue is about private and public key words .. These are not related to classes in JavaScript.. They are only in java :)

**Comment by bhaskarmelkani** [comment]
@loverajoel I will update it.
@shivarajnaidu : Hey classes in ES6 are not supported by browsers yet. This just to tell how one can you  
variables/properties that have a private scope to a function(often called as class in prototypal inheritance).

We should start using ES6 concepts but also should have idea about old techniques. :)

**Comment by bhaskarmelkani** [comment]
Closing this with updated PR #157

**Pull request closed without merging**
