### PR TITLE
Short circuit evaluation in js

### PR DESCRIPTION
**Pull request by bhaskarmelkani**

### CODE REVIEW

**Comment by shivarajnaidu** [comment]
We can simply use default parameter initialization ( new in es6).
Now we can initialize functions like this 

 ```javascript
function myfun(name="bar");
}
```

Instead of 

```javascript
function myfun(name){
 var name =name || "bar"
}
```

@bhaskarmelkani

**Comment by yuvarajvemula** [comment]
We can simply use default parameter initialization ( new in es6).
Now we can initialize functions like this 

``` javascript
function myfun(name="bar"){
var name =name;
}
```

Instead of 

``` javascript
function myfun(name){
 var name =name || "bar" ;
}
```

@bhaskarmelkani

**Comment by loverajoel** [comment]
Hi, how you can see the jstips repository changed his format and the `master` branch now is `gh-pages`, now are based in _jekyll blog format_. You can see live here => [jstips.com](http://www.jstips.co/)
For that reason you should update your tip with this [instructions](https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING.md).

Let me know if you need some help or have suggestion. All are welcome!

Thanks

**Comment by bhaskarmelkani** [comment]
Closing this with an updated PR #156

**Pull request closed without merging**
