### PR TITLE
extract unix timestamp in js

### PR DESCRIPTION
**Pull request by nurrony**
## TL;DR;

Easiest way to extract Unix Timestamp in Javascript
## Username

[@nmrony](https://github.com/nmrony)

### CODE REVIEW

**Comment by gogainda** [comment]
I think .getTime() is better than +new Date()

**Comment by kurtextrem** [comment]
@gogainda perf? Else +new Date wins, less characters.
(for current timestamp Date.now() can be used and is shorter)

**Comment by gogainda** [comment]
@kurtextrem At least is easier to understand for newcomers. `+new Date` seems like magic

**Comment by kurtextrem** [comment]
@gogainda Feel free to dive into the mechanics behind that. More knowledge for everyone! :muscle:

**Comment by nurrony** [comment]
@kurtextrem @gogainda Agreed and `getTime()` , `.now()` is performant than the magic trick. Let me add those also and send another PR with these functions. BTW- What is the Patch Template?

**Comment by zenopopovici** [comment]
@nmrony Just update the current PR. We'll add it under review in the coming days, where it can be voted by everyone. See #251

**Comment by nurrony** [comment]
@zenopopovici I have updated my PR.. Found that `date.now()` is performant than `getTime` [now vs getTime](http://jsperf.com/gettime-vs-now-0). Please have a look on PR if it is all ok or not. Thanks

**Comment by zenopopovici** [comment]
Can you clarify "magic"? :) I like the wording but + should be explained. Otherwise, it looks great to me. We'll open an issue so that the community can review this next week.

**Comment by nurrony** [comment]
@zenopopovici Under the hood the runtime calls `valueOf` method of the Date object.  Then the unary `+`  operator calls `toNumber()` with that returned value. More information can be found in the links below
[Date.prototype.valueOf](http://es5.github.io/#x15.9.5.8)
[Unary + operator](http://es5.github.io/#x11.4.6)
[toNumber()](http://es5.github.io/#x9.3)
Should I add these links in this tips? or better to remove the part? :-)

**Comment by zenopopovici** [comment]
@nmrony I know what it does :), but some of the people reading might not. Just add it to the explanation. A short sentence and link should be fine :)

**Comment by nurrony** [comment]
@zenopopovici I have added a short explanation and those links also. Please check the PR now. Hope it is fine :). Thanks

**Comment by drakmail** [comment]
:shipit:

**Comment by zenopopovici** [comment]
:shipit:

**Comment by loverajoel** [comment]
:shipit: :clap:

**Comment by loverajoel** [comment]
@gogainda @kurtextrem :shipit: ?

**Comment by nurrony** [comment]
Can I give a  :shipit: ? :smile:

**Comment by zenopopovici** [comment]
@loverajoel: Let's ship this :)

**Comment by loverajoel** [comment]
@nmrony hahah that's the reason why I proposed 3 shipits in the rules, but now is 5 :p

**Comment by kurtextrem** [comment]
:shipit: :D

**Comment by sjfkai** [comment]
:shipit:   :+1:

**Comment by loverajoel** [comment]
thanks guys!

**Pull request merged**
