### PR TITLE
Breaking or continuing loop in functional programming

### PR DESCRIPTION
**Pull request by vamshisuram**
## TL;DR;

[content attached..]
## vamshisuram

[twitter account link or github account link ej: [@vamshisuram](https://twitter.com/vamshisuram)]

### CODE REVIEW

**Comment by loverajoel** [comment]
@vamshisuram I link this one, can you add more explanation about `some()`? maybe an oficial link and jsbin demo can help!

**Comment by vamshisuram** [comment]
@loverajoel Added MDN links and quoted their description on **some** method.

**Comment by loverajoel** [comment]
the format of the file should be .md

**Comment by zenopopovici** [comment]
This is nice. :shipit:

**Comment by loverajoel** [comment]
@vamshisuram can you add a playground like this https://github.com/loverajoel/jstips/blob/gh-pages/_posts/en/2016-08-10-comma-operaton-in-js.md ?

**Comment by loverajoel** [comment]
Thanks!

**Pull request merged**
