### PR TITLE
Contrib

### PR DESCRIPTION
**Pull request by ghost**
## TL;DR;

[content here]
## Username

[twitter account link or github account link ej: [@tips-js](https://twitter.com/tips_js)]
## Extra

[content here]

Do you want to port some of the tutorials to es6 ?

### CODE REVIEW

**Comment by ghost** [comment]
It would be great if someone joins and write sass **mixins**.

**Comment by zenopopovici** [comment]
@loverajoel This should be considered. Can you test to see if everything works?

**Comment by loverajoel** [comment]
@zenopopovici @wifiextender sorry, I was out, I will test this

**Comment by zenopopovici** [comment]
@wifiextender Could you please rebase?

**Comment by zenopopovici** [comment]
Stale. Closing.

**Pull request closed without merging**
