### PR TITLE
Added template strings to tip #19

### PR DESCRIPTION
**Pull request by indianakernick**

### CODE REVIEW

**Comment by loverajoel** [comment]
@gogainda ping

**Comment by homer0** [comment]
_Template strings are only available in ES6_

**Comment by indianakernick** [comment]
The latest versions of all major browsers have ES6 (except for IE obviously)

**Comment by homer0** [comment]
@Kerndog73 my bad :disappointed: , I should've checked the support, sorry!!
To be fair, I said it was from ES6, not that it wasn't supported hahaha :P.
You can ignore my comment!

**Comment by indianakernick** [comment]
@homer0 Haha that's alright

**Comment by gogainda** [comment]
LGTM

**Comment by loverajoel** [comment]
@Kerndog73 hey can you move this fix to the correct file?

**Comment by yuvarajvemula** [comment]
:+1: dudes .. template strings are very useful thing.  Worth to know..

**Pull request closed without merging**
