### PR TITLE
Create range - new solution

### PR DESCRIPTION
**Pull request by asvny**
New range solution

### CODE REVIEW

**Comment by zenopopovici** [comment]
@annamalai-saro Please add: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by zenopopovici** [comment]
Sorry for the long delay.

**Comment by asvny** [comment]
@zenopopovici  👍

**Comment by zenopopovici** [comment]
Thank you!

**Pull request merged**
