### PR TITLE
(WIP) Translate into ru_RU

### PR DESCRIPTION
**Pull request by drakmail**
Just started translation to Russian :)

### CODE REVIEW

**Comment by loverajoel** [comment]
Woww!!! awesome!

**Comment by loverajoel** [comment]
Hi @drakmail , the structure of the repo changed and now we support multi language for the site. Please let me know when you finish to move all files to the new structure so we can merge this.
Thanks for awesome work!

**Comment by zenopopovici** [comment]
@drakmail Please let us know if you're still willing to translate jstips into Russian.

Thanks!

**Comment by drakmail** [comment]
@zenopopovici after communication with local JS group I decided doesn't translate tips by reason that most of JS programmers know English enough to understand the tips.

**Pull request closed without merging**
