### PR TITLE
Translate jstips to Chinese Translation version

### PR DESCRIPTION
**Pull request by neighborhood999**
Hi @loverajoel：
I very like jstips！That's simple and useful！
So I want to translate to Chinese Translation for my friends and other peoples for learning.
I will complete other config and something.

### CODE REVIEW

**Comment by loverajoel** [comment]
Hey @neighborhood999 what is the difference with this Chinese version? https://github.com/loverajoel/jstips/tree/gh-pages/_posts/zh_CN

**Comment by loverajoel** [comment]
@sjfkai ping!

**Comment by neighborhood999** [comment]
@loverajoel yep, different Chinese version is on diction and Chinese Translation is use by Taiwanese.

**Comment by sjfkai** [comment]
yes, we need this version, and it should be called `zh_TW`. Some differences from `zh_CN`

**Comment by neighborhood999** [comment]
Hey @loverajoel, I already setting config, please check. thank you :)

**Comment by loverajoel** [comment]
@neighborhood999 sure, I will check it today, thanks!

**Comment by sjfkai** [comment]
:+1:

**Comment by neighborhood999** [comment]
@loverajoel thank you！

**Comment by chentsulin** [comment]
:+1:

**Comment by zenopopovici** [comment]
@sjfkai Please merge this if all looks ok.

**Comment by neighborhood999** [comment]
@zenopopovici thank you！

**Comment by sjfkai** [comment]
@zenopopovici  Please  keep up with the newest tip.

And after finish that  @loverajoel maybe you should  merge this

**Comment by zenopopovici** [comment]
@sjfkai: will be more careful

**Comment by neighborhood999** [comment]
@sjfkai I already update to newest tips.

**Comment by loverajoel** [comment]
@neighborhood999 I will merge this weekend!

**Comment by loverajoel** [comment]
@neighborhood999 I merged your PR, thanks for this huge work!

I will add you administrator and you will in charge to translate tips and update tips after improvements.

Please let me know if you have any question

**Comment by neighborhood999** [comment]
@loverajoel thank you for merge！
OK, It's no problem, I will update tips and improvements.

**Comment by loverajoel** [comment]
image

Impressive visitors yesterday

**Comment by zenopopovici** [comment]
Cool :)

**Comment by neighborhood999** [comment]
I post and share this website in my facebook group.
They are so happy have zh-TW lang version!
I'm really thanks @loverajoel let me merged my translate version.

**Pull request merged**
