### PR TITLE
Added "converting to number fast way"

### PR DESCRIPTION
**Pull request by sonnyt**

### CODE REVIEW

**Comment by homer0** [comment]
Honest question, lets say `var n = '-1'`, why would I use `+/-a` instead of `Number(a)`?.
Also, [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits.

:skull: Like it!

**Comment by kurtextrem** [comment]
@homer0 because of perf and less bytes used: https://jsperf.com/number-vs-parseint-vs-plus/29

**Comment by mallowigi** [comment]
How is it easier than Number(x)?

**Comment by sonnyt** [comment]
What @kurtextrem said :smile:

**Comment by homer0** [comment]
@kurtextrem thanks :)

**Comment by loverajoel** [comment]
@sonnyp can you add a jsperf link? also mergeback and squash your commits

**Comment by sonnyp** [comment]
I think you meant @sonnyt :smiley:

**Comment by sonnyt** [comment]
@loverajoel I merged and added jsPref. Rebasing is causing bunch of problems... ugh :sob:

**Comment by sonnyt** [comment]
@sonnyp :laughing: :wave:

**Comment by loverajoel** [comment]
@sonnyt thanks for your tip man!

**Pull request merged**
