### PR TITLE
[WIP] Translate to Spanish_es_ES

### PR DESCRIPTION
**Pull request by ppollo07**
## Translate to Spanish

[@ppollo07](https://twitter.com/ppollo07)

### CODE REVIEW

**Comment by loverajoel** [comment]
:clap: :clap: :clap:

**Comment by zenopopovici** [comment]
Wow. Awesome work!

**Comment by ppollo07** [comment]
Thanks! @zenopopovici

**Comment by loverajoel** [comment]
@ppollo07 ping

**Comment by ppollo07** [comment]
@loverajoel i need your check for my new commits.. It's all ready!!

**Comment by loverajoel** [comment]
Thanks @ppollo07

**Pull request merged**
