### PR TITLE
Added a new tip

### PR DESCRIPTION
**Pull request by madhur**

### CODE REVIEW

**Comment by madhur** [comment]
Is this pull request going to be accepted? Let me know if any changes are required.

**Comment by loverajoel** [comment]
@madhur sure, please make a rebase and move your tip to top of the tips.
This tip will be merged the 2016-01-09.
Adapt you tip to the [rules](https://github.com/loverajoel/jstips/blob/master/CONTRIBUTING.md)

**Comment by loverajoel** [comment]
- Add link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators

**Comment by loverajoel** [comment]
closed by inactivity

**Pull request closed without merging**
