### PR TITLE
Alternate revamp of Tip 33

### PR DESCRIPTION
**Pull request by gromgit**
## TL;DR;

Compact one-liners that generate ordinal sequence arrays
## Username

[gromgit](https://github.com/gromgit)
## Extra
- Shorter explanation that should be sufficient for intermediate-level JS developers
- Original exposition now in my own repo, link in text

### CODE REVIEW

**Comment by gromgit** [comment]
Related to this, I've started the [jstips-xe](https://github.com/gromgit/jstips-xe) repo to collect any explanations I may write which are too long to fit in 2 minutes.

@SarjuHansaliya , please let us know which revamp you refer, or if you have some other ideas. Thanks.

**Comment by adaniloff** [comment]
@gromgit @loverajoel  I like the way it is with this new repo.

I think it could be interesting to include those directly in the jstip repo, with two distinct "room" (one accessible from the readme, the other one only accessible from each tip when an explanation is desired).

What do you think guys ?

**Comment by zenopopovici** [comment]
I prefer this too.

**Comment by SarjuHansaliya** [comment]
@gromgit  @loverajoel 
This idea looks good.
If someone doesn't know some basic then one can relate it.

**Comment by SarjuHansaliya** [comment]
@loverajoel  We can close this now ?

**Comment by loverajoel** [comment]
@SarjuHansaliya sorry? I merged this based in your comment 
image

**Comment by SarjuHansaliya** [comment]
yes I also mean to merge #313 only

**Pull request merged**
