### PR TITLE
Use === instead of ==.

### PR DESCRIPTION
**Pull request by bhaskarmelkani**

### CODE REVIEW

**Comment by kurtextrem** [comment]
Link to a jsperf would be great :+1:

**Comment by bhaskarmelkani** [comment]
@kurtextrem : Adding Jspref :)

**Comment by loverajoel** [comment]
Hi, how you can see the jstips repository changed his format and the `master` branch now is `gh-pages`, now are based in _jekyll blog format_. You can see live here => [jstips.com](http://www.jstips.co/)
For that reason you should update your tip with this [instructions](https://github.com/loverajoel/jstips/blob/gh-pages/CONTRIBUTING.md).

Let me know if you need some help or have suggestion. All are welcome!

Thanks

**Comment by bhaskarmelkani** [comment]
Hey, I have updated the branch as suggested. Should I close this PR and raise a new against gh-pages ?

**Comment by bhaskarmelkani** [comment]
Closing this for #154

**Pull request closed without merging**
