### PR TITLE
Changed all "Fat Arrow Functions" to just "Arrow Functions" with the …

### PR DESCRIPTION
**Pull request by yird**
…exception of the explanation on the differences of `=>` and `->`.

Minor spelling fixes.

### CODE REVIEW

**Comment by loverajoel** [comment]
@pklinger ping

**Comment by pklinger** [comment]
@Yird I'd say leave the title as it is (catchy) to draw attention and to keep the tip in memory, but change the rest of the article as you did.  Thanks for the PR.

**Comment by loverajoel** [comment]
@Yird hey can you move this fix to the new file?

**Comment by yird** [comment]
@pklinger @loverajoel Sorry it took a while to respond. Well the official name for it is just Arrow Function. Fat might be more catchy but I think these tips should be more accurate to the standard.

**Pull request closed without merging**
