### PR TITLE
Translate to Russian [ru_RU] [WIP]

### PR DESCRIPTION
**Pull request by crecotun**
Hi, I'm working on Russian translation and have finished 2 articles so far :)

What is better: translate all tips and then merge or translate and merge one by one?

Also there was a problem with Arvo font. It doesn't have cyrillic symbols, so I decided to change it to Roboto Slab. It looks almost the same, but let me know if there is a better alternative.

**Progress:**
- [x] Insert item inside an Array
- [x] AngularJs - $digest vs $apply
- [x] Keys in children components are important
- [x] Improve Nested Conditionals
- [x] Sorting strings with accented characters
- [x] Differences between undefined and null
- [x] Writing a single method for arrays and a single element
- [x] use strict and get lazy
- [x] Converting a Node List to an Array
- [x] Template Strings
- [x] Check if a property is in a Object
- [x] Hoisting
- [x] Pseudomandatory parameters in ES6 functions
- [x] Tip to measure performance of a javascript block
- [ ] Fat Arrow Functions
- [ ] Even simpler way of using indexOf as a contains clause
- [ ] Passing arguments to callback functions
- [ ] Node.js - Run a module if it is not required
- [ ] Truncating the fast (but risky) way
- [ ] Safe string concatenation
- [ ] Return objects to enable chaining of functions
- [ ] Shuffle an Array
- [ ] Two ways to empty an array
- [ ] Converting to number fast way
- [ ] Use === instead of ==
- [ ] Using immediately invoked function expression
- [ ] Filtering and Sorting a List of Strings
- [ ] Short circuit evaluation in JS.
- [ ] Currying vs partial application
- [ ] Speed up recursive functions with memoization
- [ ] Converting truthy/falsy values to boolean
- [ ] Avoid modifying or passing arguments into other functions — it kills optimization
- [ ] Map() to the rescue; adding order to Object properties
- [ ] Create array sequence [0, 1, ..., N-1] in one line
- [ ] Implementing asynchronous loop
- [ ] Assignment Operators
- [ ] Observe DOM changes in extensions
- [ ] Deduplicate an Array
- [ ] Flattening multidimensional Arrays in JavaScript
- [ ] Advanced Javascript Properties
- [ ] Using JSON.Stringify
- [ ] Array average and median
- [ ] Preventing Unapply Attacks
- [ ] Use destructuring in function parameters
- [ ] Know the passing mechanism
- [ ] Calculate the Max/Min value from an array
- [ ] Detect document ready in pure JS
- [ ] Basics declarations
- [ ] How to reduce() arrays
- [ ] Easiest way to extract unix timestamp in JS
- [ ] Helpful Console Logging Tricks
- [ ] DOM event listening made easy
- [ ] Return Values with the ‘new’ Operator
- [ ] Get File Extension
- [ ] How to use optional arguments in functions (with optional callback)
- [ ] Create an easy loop using an array
- [ ] Copy to Clipboard
- [ ] Comma operator in JS
- [ ] Breaking or continuing loop in functional programming
- [ ] ES6, var vs let
- [ ] Three useful hacks
- [ ] Binding objects to functions

### CODE REVIEW

**Comment by loverajoel** [comment]
Awesome!!! 😎
Translate all tips is better. I will take a look to the new font!

**Comment by crecotun** [comment]
Thanks :)

**Comment by zenopopovici** [comment]
Nice work :)

**Comment by crecotun** [comment]
@zenopopovici thanks, it will be a very long road :)

@loverajoel I've an idea. It's a bit sad to work without a visual progress and validation from russian community, so I decided to publish translated parts to my blog (of course, I'll give a link to the original resource). 

Can I do this?

**Comment by zenopopovici** [comment]
@Krekotun The project is GPL. https://github.com/loverajoel/jstips/blob/gh-pages/LICENSE.md

It think it should be OK.

**Comment by crecotun** [comment]
@zenopopovici cool :)

**Comment by crecotun** [comment]
I have no time to work on translation for a long period. I've noticed a lot of changes in the repo.
What should I change to make it up to date? (I see no blog generator)
@loverajoel

**Pull request closed without merging**
