### PR TITLE
typeof without parentheses

### PR DESCRIPTION
**Pull request by matjaz**

### CODE REVIEW

**Comment by rocketinventor** [comment]
@matjaz Why don't you change it to show both methods?

**Comment by matjaz** [comment]
there is no both ways. `typeof` is a keyword and thus not requiring parentheses.

**Comment by rocketinventor** [comment]
@matjaz Yah, you are right. Good catch!

**Comment by loverajoel** [comment]
sorry guys my bad, thanks!

**Comment by manmadareddy** [comment]
@loverajoel
Next to this tip you can also add
if (Object.hasOwnProperty('key'))
To check 'key' is defined for a object or not.

**Comment by rocketinventor** [comment]
@manmadareddy Can you provide an example for that?

**Comment by manmadareddy** [comment]
@rocketinventor 

``` javascript
var obj = new Object();
obj.prop1 = 'exists';
if (obj.hasOwnProperty('prop1')) {
    console.log('prop1 exist');
}
if (!obj.hasOwnProperty('prop2')) {
    console.log('prop2 not exist');
}
```

Tip#3 uses the same.
https://github.com/loverajoel/jstips#03---improve-nested-conditionals

**Comment by matjaz** [comment]
`new Object()` is anti-pattern. use `{}`.

**Comment by aaron-goshine** [comment]
@matjaz @rocketinventor hello guys `new Object()` use to be an anti pattern with es6/7 that is changing quickly

**Comment by matjaz** [comment]
can you elaborate? any links?

**Pull request merged**
