### PR TITLE
Mention spread operator in Node List to an Array section

### PR DESCRIPTION
**Pull request by ahmedelgabri**

### CODE REVIEW

**Comment by kurtextrem** [comment]
Is there any way to test performance?

**Comment by ahmedelgabri** [comment]
I'm sure there is but perf tests in the wild doesn't make sense to me to be honest

**Comment by loverajoel** [comment]
@tevko ping

**Comment by tevko** [comment]
:+1:

**Comment by loverajoel** [comment]
thanks

**Pull request merged**
