### PR TITLE
Compress HTML

### PR DESCRIPTION
**Pull request by marcobiedermann**
- add compress.html
- fix wrong markdown semantic

This will save some bytes over bandwidth

### CODE REVIEW

**Comment by yuvarajvemula** [comment]
What is this {{}}

**Comment by marcobiedermann** [comment]
This Layout will remove compress your HTML.

It will:
- removes unnecessary whitespace
- removes optional end tags
- removes optional start tags
- removes comments
- preserves whitespace within `<pre>`

You will find more information about this [here](http://jch.penibelst.de/)

**Comment by yuvarajvemula** [comment]
Oh.. You are telling this to use in this website..??

**Comment by marcobiedermann** [comment]
Yes. Minifying content is always recommended.

**Comment by yuvarajvemula** [comment]
What library is it yar ??

**Comment by marcobiedermann** [comment]
The layout is hosted on this repo: https://github.com/penibelst/jekyll-compress-html

**Comment by yuvarajvemula** [comment]
:+1:

**Comment by zenopopovici** [comment]
@marcobiedermann Please pull changes and rebase your work on top of it. We only want your changes in the PR. 

Thanks.!

**Comment by zenopopovici** [comment]
@loverajoel We should at least test this.

**Comment by zenopopovici** [comment]
Stale. Closing.

**Pull request closed without merging**
