### PR TITLE
[WIP] Translate to Spanish_ES

### PR DESCRIPTION
**Pull request by ppollo07**
## [WIP] Translate to Spanish_ES

Translate to Spanish
## Twitter

[@ppollo07](https://twitter.com/ppollo07)

### CODE REVIEW

**Comment by loverajoel** [comment]
You have files for CH in your PR, please make a rebase and only send Spanish lang.

Also, good work!

**Comment by ppollo07** [comment]
Toote magic!! haha
Ready to merge

**Comment by zenopopovici** [comment]
@ppollo07 Thank you for your work, we'll lot over it asap.

**Comment by loverajoel** [comment]
@ppollo07 you still have conflicts, there are files from EN language

**Pull request closed without merging**
