### PR TITLE
#Easy forEach operation

### PR DESCRIPTION
**Pull request by sekaiamber**
using a simple regular expression to make an easy `forEach` operation. :)

### CODE REVIEW

**Comment by drakmail** [comment]
Very interesting tip! Does it just another approach to `.split(",").forEach`? Does it perform better? Readability is not better part of this method of iteration :)

**Comment by sekaiamber** [comment]
@darkmail it seems that `Array.prototype.forEach` is not supported in IE8 :(.  
Speaking about performance, I use following test case in my Chrome console:

``` javascript
var i = 0;
var str = Array(20000).join(',').split(',').map(function(a) {return 'f' + i++}).join(','); // str = "f0,f1,f2,f..."
var target = {};
console.time('using_reg');
str.replace(/[^, ]+/g, function (name) {
  target[name] = name;
});
console.timeEnd('using_reg'); // using_reg: 28.739ms

str = Array(20000).join(',').split(',').map(function(a) {return 'f' + i++}).join(','); // str = "f0,f1,f2,f..."
target = {};
console.time('using_split');
str.split(",").forEach(function (name) {
  target[name] = name;
});
console.timeEnd('using_split'); // using_split: 29.263ms
```

It seems that using regular expression is a little bit faster then using `split`, and `split` will create a new array in memory but regular expression not.

And `/[^, ]+/g` can deal with string like `"p1, p2 ,p3,     p4"`, it will ignore the space in the string, this is better then using `split` :)

**Comment by homer0** [comment]
Pretty nice!!! I didn't know this. Now, I did a [jsperf test](http://jsperf.com/regexp-loop-vs-split-loop/2) and, except for Opera, it looks like the `split` _loop_ it's faster... but anyway, it's a nice trick/tip to know :).

:skull:

**Comment by sekaiamber** [comment]
@homer0 Thank you for the test :), and I test again and found if the length of the array is small, `split` will win, I think it is because when splitting a big string, make a new big array will cast a long time.  
In most instances, the string is short, and the performance between these 2 way is extremely close, we can almost ignore it.

**Comment by homer0** [comment]
@sekaiamber agree :+1:

**Comment by mallowigi** [comment]
Why is it better than ["foo","bar"].forEach ?

**Comment by 1robertrb** [comment]
cool tip! :stars:

**Comment by 1robertrb** [comment]
is replace not more like map than forEach? it definitely seems like it, if you used an explicit return, so perhaps you should allude to that in the documentation.

**Comment by 1robertrb** [comment]
@mallowigi thats a good point, i think the forEach pull request has much better value. this probably confuses people more than anything.

**Comment by sekaiamber** [comment]
@mallowigi @strcmp Yes, you are right:). I think `forEach` is more readable. This tip more like a promise of code style in a project:) It may reduce the code size, and use the regular expression to do other things. See [this](https://github.com/RubyLouvre/avalon/blob/master/avalon.js#L3340), and [this](https://github.com/RubyLouvre/avalon/blob/master/avalon.js#L1113) is use to instead of `.split(',')`.  

Thanks for the point :)

**Comment by zenopopovici** [comment]
@sekaiamber Can you please rebase your work on top of the latest commit? We're changing rules (see: #251), and we want to submit your tip for review.

**Comment by sekaiamber** [comment]
@zenopopovici Please see #267 ,and I'll close this PR :)

**Comment by zenopopovici** [comment]
Thank you!

**Pull request closed without merging**
