### PR TITLE
Added tip for writing a single method for arrays or a single element

### PR DESCRIPTION
**Pull request by mattfaluotico**
You can easily make a single methods work for an array of inputs or a single input by concatting the parameter into an array.

### CODE REVIEW

**Comment by loverajoel** [comment]
Awesome, tomorrow will be merged! Please squash your commits.
Thanks for your contribution!

**Comment by mattfaluotico** [comment]
Squashed :+1:

**Comment by loverajoel** [comment]
Thanks!

**Comment by davidchambers** [comment]
This strikes me as unnecessary and undesirable. If one wants to provide one value to a function which accepts an array, simply provide a one-element array!

``` diff
-printUpperCase("cactus");
+printUpperCase(["cactus"]);
```

**Comment by loverajoel** [comment]
@mattfxyz https://github.com/loverajoel/jstips/issues/42 and https://github.com/loverajoel/jstips/issues/27

**Comment by anselmbradford** [comment]
+1 to @davidchambers
It seems beneficial to aim for inputs and outputs into a function that do not change data type. Introducing logic to handle a change in an argument's data type because the argument value isn't type-safe makes functions unnecessarily complex and prone to runtime errors. ESLint has a consistent return type rule for [this reason](http://eslint.org/docs/rules/consistent-return.html).

**Pull request merged**
