### PR TITLE
wording and follow recently updated.(zh_TW)

### PR DESCRIPTION
**Pull request by neighborhood999**
## TL;DR;

as title
## Username

[neighborhood999](https://github.com/neighborhood999)

### CODE REVIEW

**Comment by loverajoel** [comment]
@neighborhood999 you are admin and you can merge your fixes for this language

**Comment by neighborhood999** [comment]
@loverajoel I know :smile: 
but I not finish, I will as soon as possible.

**Comment by loverajoel** [comment]
@neighborhood999 haha sorry

**Comment by neighborhood999** [comment]
@loverajoel It's OK. I just want this translate will be better.
I want go to sleep. Good Night :smile:

**Comment by sjfkai** [comment]
:+1:  awesome work!

**Comment by zenopopovici** [comment]
Really cool! :+1:

**Pull request merged**
